fieldLayouts:
  4119e379-c51f-4861-aaa8-1ac068f84a59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7be81a07-42c0-433d-b201-fc845de4eb80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 318548c3-8af8-4fa4-816d-2af51d265170
        userCondition: null
fs: photos
handle: photos
name: photos
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: photos
transformSubpath: ''
