columnSuffix: xsfdmuot
contentColumnType: string(80)
fieldGroup: 5b6560c0-c44b-45ee-b20f-464179aab1fe # Homepage
handle: buttonText
instructions: 'What does the button say?'
name: 'Button Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 20
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
