columnSuffix: sljjdmag
contentColumnType: integer(10)
fieldGroup: 4f5a0094-e716-4456-bd4d-c44226bba9b4 # Piece
handle: edition
instructions: 'Many many of there are there?'
name: Edition
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
