columnSuffix: sgkjuxfs
contentColumnType: smallint(4)
fieldGroup: 4f5a0094-e716-4456-bd4d-c44226bba9b4 # Piece
handle: pirority
instructions: 'Number from 1 - 1000 dictating in which order the piece should appear'
name: Pirority
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 1000
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
