defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  4aa56010-c8e2-47b7-9305-9261f896e3bb: # dev.evejansenart.com
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
